# Config file path
configFile = "./config.yaml"

# Declare variables
turnAngle = None
velocity = None
wheelDistance = None
temperature = None
gravityAcceleration = None
gasContent = None
roadWidth = None
mass = None
staticFriction = None
cdValue = None
frontArea = None
turnIncline = None
atmosphericPressure = None
simulationIterations = None
functionT = None
inaccuracyTolerance = None
curveAngle = None

weight_mass = None
weight_staticFriction = None
weight_turnIncline = None
weight_cdValue = None
weight_frontArea = None
weight_atmosphericPressure = None
f_drag = None
f_velocity = None
f_new_velocity = None
f_centrifugal = None
f_gravity = None
f_gravity_parallel = None
f_neutral = None
f_road = None
f_static_friction = None
f_centripetal = None
radius = None
totalDistance = None
dataList = []
simulationIterations = None
functionT = None
inaccuracyTolerance = None
curveAngle = None
CONSTRAINTS = {}
